#!/usr/bin/env node
// Builds the docs page and the hosted copy of the script.
//
//   npm install -g bookmarklet   # once (or: npx --package bookmarklet node build.js)
//   node build.js
//
// Outputs:
//   ../docs/wikipedia-edit-history-colors/index.html  (drag-to-bookmark page)
//   ../docs/wikipedia-edit-history-colors.js          (loaded by loader.js)
const fs = require('fs');
const path = require('path');

let bookmarklet;
try {
  bookmarklet = require('bookmarklet');
} catch (e) {
  bookmarklet = require(path.join(require('child_process').execSync('npm root -g').toString().trim(), 'bookmarklet'));
}

const here = __dirname;
const docs = path.join(here, '..', 'docs');

async function compile(file) {
  const { code, options, errors } = bookmarklet.parseFile(fs.readFileSync(path.join(here, file), 'utf8'));
  if (errors) throw new Error(errors.join('\n'));
  return { url: await bookmarklet.convert(code, options), name: options.name };
}

function escapeAttr(s) {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

(async () => {
  const full = await compile('source.js');
  const loader = await compile('loader.js');
  fs.copyFileSync(path.join(here, 'source.js'), path.join(docs, 'wikipedia-edit-history-colors.js'));

  const html = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wikipedia Edit History Colors</title>
    <style>
      html,body,div { margin: 0; padding: 0; font: normal 16px/24px Helvetica Neue, Helvetica, sans-serif; color: #333; }
      #main { max-width: 630px; margin: 3em auto; padding: 0 16px; }
      .bookmarklet { display: inline-block; padding: .5em 1em; color: #fff; background: #50dcf3; border-radius: 4px; text-decoration: none; }
      .bookmarklet.alt { background: #999; }
      a { color: #50dcf3; }
      .dim { color: #999; }
      .ramp { height: 18px; border-radius: 4px; border: 1px solid #888; background: linear-gradient(to right, oklch(0.2 0.13 28), oklch(0.352 0.13 60), oklch(0.504 0.13 98), oklch(0.656 0.13 142), oklch(0.808 0.13 258), oklch(0.96 0.13 305)); }
      .labels { display: flex; justify-content: space-between; font-size: 13px; color: #666; }
      code { background: #f3f3f3; padding: 1px 4px; border-radius: 3px; }
      li { margin-bottom: .4em; }
    </style>
  </head>
  <body>
    <div id="main">
      <h1>Wikipedia Edit History Colors</h1>
      <p>
        Colors every word of a Wikipedia article by <em>when it was added</em>, and lets you
        triple-click any word to see the section as it looked in the edit that added it.
      </p>
      <p>
        Drag this button to your bookmarks bar to save it as a bookmarklet, then click it on any Wikipedia article:
      </p>
      <p>
        <a class="bookmarklet" href="${escapeAttr(full.url)}">${full.name}</a>
      </p>
      <p class="dim">
        If your browser refuses long bookmark URLs, use this loader version instead (it fetches the script from this site):
        <a class="bookmarklet alt" href="${escapeAttr(loader.url)}">${loader.name}</a>
      </p>

      <h2>How to read it</h2>
      <div class="ramp"></div>
      <div class="labels"><span>oldest (black / red)</span><span>newest (violet / white)</span></div>
      <ul>
        <li>The ramp runs <strong>red → orange → yellow → green → blue → violet</strong> from the article's first edit to its latest one.</li>
        <li>Lightness climbs monotonically from black to white along the ramp, so the ordering is still readable in grayscale or with any form of color blindness. Text sits on the color in black or white for contrast. The <strong>Mono</strong> button drops the hue entirely, <strong>Ink</strong> colors the letters instead of the background, and <strong>⇄</strong> reverses the direction.</li>
        <li>Spaces are never colored. Words that only exist in the rendered page (infobox labels, navigation text, anything generated by a template) get a dotted underline instead of a color.</li>
        <li>Hover a word for the date range it was added in. <strong>Triple-click or triple-tap</strong> a word to pinpoint the exact revision and open a 60%-inset popup showing that section as it was then, scrolled so the word is centered and highlighted. Esc or the backdrop closes it.</li>
        <li>Click the bookmarklet again (or the ✕ in the legend) to restore the page.</li>
      </ul>

      <h2>How it works</h2>
      <p>
        Only Wikipedia's own API is used, so it works on every language edition. The article's history is sampled
        at evenly spaced points in time (plus extra samples where most of the text landed); each word of the current
        wikitext is dated to the earliest sample that already contains it together with a neighbouring word, then the
        rendered page is aligned back to the wikitext to paint it. Triple-clicking runs a binary search between the two
        surrounding samples to find the exact edit.
      </p>
      <p>See source at <a href="https://github.com/cwervo/bookmarklets/tree/master/wikipedia-edit-history-colors">github.com/cwervo/bookmarklets</a>.</p>
      <p class="dim">This page was created with the <a href="https://github.com/mrcoles/bookmarklet">bookmarklet</a> npm library.</p>
    </div>
  </body>
</html>
`;
  fs.mkdirSync(path.join(docs, 'wikipedia-edit-history-colors'), { recursive: true });
  fs.writeFileSync(path.join(docs, 'wikipedia-edit-history-colors', 'index.html'), html);
  console.log('wrote docs/wikipedia-edit-history-colors/index.html (' + full.url.length + ' char bookmarklet) and docs/wikipedia-edit-history-colors.js');
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
